name = "ts-do"
# type = "javascript" is required to use the `[build]` section
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-02-10"

[build]
command = ""
[build.upload]
# The "modules" upload format is required for all projects that export a Durable Objects class
format = "modules"
main = "./index.mjs"

[durable_objects]
bindings = [
    {name = "CustomerDo", class_name = "CustomerDo"},
    {name = "FeatureToggleDo", class_name = "FeatureToggleDo"}
]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["CounterTs"]
